apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: wanderlust
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: backend
          image: docker-test.wakeb.tech/wanderlust/wanderlust-backend-beta:1.34
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo-service/wanderlust"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: FRONTEND_URL
              value: "http://frontend-service:5173"
            - name: ACCESS_COOKIE_MAXAGE
              value: "120000"
            - name: ACCESS_TOKEN_EXPIRES_IN
              value: "120s"
            - name: REFRESH_COOKIE_MAXAGE
              value: "120000"
            - name: REFRESH_TOKEN_EXPIRES_IN
              value: "120s"
            - name: JWT_SECRET
              value: "70dd8b38486eee723ce2505f6db06f1ee503fde5eb06fc04687191a0ed665f3f98776902d2c89f6b993b1c579a87fedaf584c693a106f7cbf16e8b4e67e9d6df"
            - name: NODE_ENV
              value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wanderlust
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31100
