apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: wanderlust
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXItaG9zdGVkLm5lZWRvby5pbiI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZSV1ZxYTBBeE9UZzIiCgkJfSwKCQkiZG9ja2VyLXByb3h5Lm5lZWRvby5pbiI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZSV1ZxYTBBeE9UZzIiCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJjMkZzWldWcWEzVnlkVzVwZVdGdU9tUmphM0pmY0dGMFgwZEJORWxyUTI4M00wUnJhVlJ6Vld0dGNrNHhRbWxoUlVGaWR3PT0iCgkJfQoJfQp9