apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: wanderlust
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXItaG9zdGVkLXRlc3Qud2FrZWIudGVjaCI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZSV1ZxYTBBeE9UZzIiCgkJfSwKCQkiZG9ja2VyLXByb3h5LXRlc3Qud2FrZWIudGVjaCI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZSV1ZxYTBBeE9UZzIiCgkJfQoJfQp9

