apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: wanderlust
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IubmVlZG9vLmluIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NlJXVnFhMEF4T1RnMiIKCQl9Cgl9Cn0=

