@Library('Shared') _
pipeline {
    agent none
    
    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }
    stages {
        stage('Prepare Agent') {
            agent {
                kubernetes {
                    label 'kaniko-agent'
                    defaultContainer 'jnlp'
yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - sleep
      args:
        - infinity
      tty: true
    - name: maven
      image: maven:3.8.1-jdk-11
      command:
        - sleep
      args:
        - infinity
      tty: true
"""
                }
            }
            stages {
                stage("Workspace cleanup"){
                    steps{
                        script{
                            cleanWs()
                        }
                    }
                }
                
                stage('Git: Code Checkout') {
                    steps {
                        script{
                            code_checkout("https://github.com/saleejkuruniyan/Wanderlust-Mega-Project.git","nutanix")
                        }
                    }
                }
                
                stage('Verify: Docker Image Tags') {
                    steps {
                        script{
                            echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                            echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                        }
                    }
                }
                
                
                stage("Update: Kubernetes manifests"){
                    steps{
                        script{
                            dir('kubernetes'){
                                sh """
                                    sed -i -e s/wanderlust-backend-beta.*/wanderlust-backend-beta:${params.BACKEND_DOCKER_TAG}/g backend.yaml
                                """
                            }
                            
                            dir('kubernetes'){
                                sh """
                                    sed -i -e s/wanderlust-frontend-beta.*/wanderlust-frontend-beta:${params.FRONTEND_DOCKER_TAG}/g frontend.yaml
                                """
                            }
                            
                        }
                    }
                }
                
                stage("Git: Code update and push to GitHub"){
                    steps{
                        script{
                            withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                                sh '''
                                echo "Checking repository status: "
                                git status
                            
                                echo "Adding changes to git: "
                                git add .
                                
                                echo "Configuring Git identity: "
                                git config user.name "Jenkins CI"
                                git config user.email "saleejkuruniyan@gmail.com"
                                            
                                echo "Commiting changes: "
                                git commit -m "Updated environment variables"
                                
                                echo "Pushing changes to github: "
                                git push https://github.com/saleejkuruniyan/Wanderlust-Mega-Project.git nutanix
                            '''
                            }
                        }
                    }
                }
            }
        post {
                success {
                    script {
                        emailext attachLog: true,
                        from: 'saleejkuruniyan@gmail.com',
                        subject: "Wanderlust Application has been updated and deployed - '${currentBuild.result}'",
                        body: """
                            <html>
                            <body>
                                <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                                    <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                                </div>
                                <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                                    <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                                </div>
                                <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                                    <p style="color: black; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                                </div>
                            </body>
                            </html>
                    """,
                    to: 'saleejkuruniyan@gmail.com',
                    mimeType: 'text/html'
                    }
                }
            failure {
                    script {
                        emailext attachLog: true,
                        from: 'saleejkuruniyan@gmail.com',
                        subject: "Wanderlust Application build failed - '${currentBuild.result}'",
                        body: """
                            <html>
                            <body>
                                <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                                    <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                                </div>
                                <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                                    <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                                </div>
                            </body>
                            </html>
                    """,
                    to: 'saleejkuruniyan@gmail.com',
                    mimeType: 'text/html'
                    }
                }
            }
        }    
    }
}
